### ISSUE TITLE
视频拼接好像不太对？

### ISSUE THREAD

**Issue by yushiwo** [codeqian/ffmpegCLDemo#11]
如题，使用视频拼接功能时，合成的视频内容和时间都不太对的上。请问你那边有碰到这个问题吗

**Comment by codeqian** [comment]
这个描述也太笼统了吧。另外，我目前拼接的视频都达到预期效果。

**Comment by yushiwo** [comment]
嗯，我之前用的是demo直接跑，这样是有问题的，视频拍摄的时候显示设置编码和输出的格式为mp4之后，问题解决了
